# Generated by Django 5.2.16 on 2026-07-08 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('OnHold', 'On Hold'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Planning', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('PROJECT_CREATED', 'Project created'), ('PROJECT_UPDATED', 'Project updated'), ('MEMBER_ADDED', 'Member added'), ('MEMBER_REMOVED', 'Member removed'), ('TASK_CREATED', 'Task created'), ('TASK_UPDATED', 'Task updated'), ('TASK_STATUS_CHANGED', 'Task status changed'), ('TASK_PROGRESS_CHANGED', 'Task progress changed'), ('TASK_ASSIGNED', 'Task assigned'), ('COMMENT_ADDED', 'Comment added'), ('ATTACHMENT_UPLOADED', 'Attachment uploaded')], max_length=30, verbose_name='verb')),
                ('target_type', models.CharField(max_length=30, verbose_name='target type')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='target id')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='projects.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Member', 'Member')], default='Member', max_length=20, verbose_name='role')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project membership',
                'verbose_name_plural': 'project memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project', 'created_at'], name='projects_ac_project_c2c0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['verb', 'created_at'], name='projects_ac_verb_2673c8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'user'], name='projects_pr_project_710ab3_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_membership'),
        ),
    ]
